### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'dtype'

### ISSUE THREAD

**Issue by R-E-Y-Z-I-K** [skshadan/TTS-RVC-API#8]
Hello, when I run your code I get the error indicated in the title, how can I solve it? In addition, I would like to use this repository for TTS in other languages ​​or in general multilingual, I tried changing the TTS model from coquiTTS, but I still get "Artifact voice" when using a text other than English. How can I fix this? (Machine translation was used)

`500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    response = await self.dispatch_func(request, call_next)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\app\main.py", line 70, in log_requests
    response = await call_next(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    raise app_exc
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    raise e
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\routing.py", line 273, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\app\routers\full.py", line 23, in generate
    rvc_speaker_id, wav = server(
                          ^^^^^^^
  File "D:\AssistProj\TTS-RVC-API-main\app\routers\tts.py", line 88, in server
    write(wav, wav_opt[1][0], wav_opt[1][1])
  File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\scipy\io\wavfile.py", line 771, in write
    dkind = data.dtype.kind
            ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'dtype'

During handling of the above exception, another exception occurred:

  + Exception Group Traceback (most recent call last):
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\uvicorn\protocols\http\h11_impl.py", line 408, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 84, in __call__
  |     return await self.app(scope, receive, send)
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\applications.py", line 289, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\applications.py", line 122, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\errors.py", line 184, in __call__
  |     raise exc
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\errors.py", line 162, in __call__
  |     await self.app(scope, receive, _send)
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 106, in __call__
  |     async with anyio.create_task_group() as task_group:
  |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\anyio\streams\memory.py", line 97, in receive
    |     return self.receive_nowait()
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\anyio\streams\memory.py", line 92, in receive_nowait
    |     raise WouldBlock
    | anyio.WouldBlock
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 78, in call_next
    |     message = await recv_stream.receive()
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\anyio\streams\memory.py", line 112, in receive
    |     raise EndOfStream
    | anyio.EndOfStream
    |
    | During handling of the above exception, another exception occurred:
    |
    | Traceback (most recent call last):
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 108, in __call__
    |     response = await self.dispatch_func(request, call_next)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\app\main.py", line 70, in log_requests
    |     response = await call_next(request)
    |                ^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 84, in call_next
    |     raise app_exc
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\base.py", line 70, in coro
    |     await self.app(scope, receive_or_disconnect, send_no_error)
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    |     raise exc
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    |     await self.app(scope, receive, sender)
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 20, in __call__
    |     raise e
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\middleware\asyncexitstack.py", line 17, in __call__
    |     await self.app(scope, receive, send)
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 718, in __call__
    |     await route.handle(scope, receive, send)
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 276, in handle
    |     await self.app(scope, receive, send)
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\starlette\routing.py", line 66, in app
    |     response = await func(request)
    |                ^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\routing.py", line 273, in app
    |     raw_response = await run_endpoint_function(
    |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\fastapi\routing.py", line 190, in run_endpoint_function
    |     return await dependant.call(**values)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\app\routers\full.py", line 23, in generate
    |     rvc_speaker_id, wav = server(
    |                           ^^^^^^^
    |   File "D:\AssistProj\TTS-RVC-API-main\app\routers\tts.py", line 88, in server
    |     write(wav, wav_opt[1][0], wav_opt[1][1])
    |   File "D:\AssistProj\TTS-RVC-API-main\venv\Lib\site-packages\scipy\io\wavfile.py", line 771, in write
    |     dkind = data.dtype.kind
    |             ^^^^^^^^^^
    | AttributeError: 'NoneType' object has no attribute 'dtype'
    +------------------------------------
`

**Comment by EdVollmond** [comment]
@R-E-Y-Z-I-K , bro, how did you fix this problem?
